### ISSUE TITLE
Doesn't handle UTF-8 correct.

### ISSUE THREAD

**Issue by ghost** [syssgx/xml.js#1]
UTF-8 files results in an error:
"parser error : Input is not proper UTF-8, indicate encoding !"

Try any and you will see.

Could you fix that?

**Comment by syssgx** [comment]
"It might be possible to fix, if it's an issue that has to do with how utf-8 files are loaded on the browser page. You'll have to check first if the xmllist itself works ok with this." by Merg1255.

Indeed. If I make a new version of the project where there's time for it, I'll see how utf-8 encoding works with the uploaded files.

**Comment by ghost** [comment]
Thanks for the fast feedback. It looks like xml.js is at the moment the only js lib to validate xml schema. Saxon CE doesn't support it yet.
